<?php

/**
 * @file
 * The paraseed_slider.module.
 */

use Drupal\views\ViewExecutable;
use Drupal\media\Entity\Media;

/**
 * Implements hook_views_pre_render().
 */
function paraseed_slider_views_pre_render(ViewExecutable $view) {
  if (isset($view) && ($view->storage->id() == 'paraseed_slider')
      && count($view->result) < 1) {
    // Default empty view style.
    $view->element['#attached']['library'][] = 'paraseed_slider/view-empty';
  }
}

/**
 * Implements hook_theme().
 */
function paraseed_slider_theme($existing, $type, $theme, $path) {
  return [
    'node__paraseed_slider' => [
      'template' => 'node--paraseed-slider',
      'base hook' => 'node',
    ],
    'media_oembed_iframe__remote_video__paraseed_slider' => [
      'template' => 'media-oembed-iframe--remote-video--paraseed-slider',
      'variables' => [
        'provider' => NULL,
        'media' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function paraseed_slider_preprocess_media_oembed_iframe__remote_video__paraseed_slider(&$variables) {
  // Send variables for the remote_video paraseed media hero slier oembed iframe.
  $query = \Drupal::request()->query;
  $variables['type'] = $query->get('type');
  $variables['provider'] = $query->get('provider');
  $variables['view_mode'] = $query->get('view_mode');
  $variables['base_path'] = base_path();
  $variables['paraseed_slider_path'] = \Drupal::service('module_handler')->getModule('paraseed_slider')->getPath();
}

/**
 * Implements hook_preprocess_node_HOOK().
 */
function paraseed_slider_preprocess_node__paraseed_slider(&$variables) {

  $node = $variables['elements']['#node'];
  $media = $node->get('field_media_single')->getValue();

  if (!empty($media)) {
    // var_dump($media);
    $entity = Media::load($media[0]['target_id']);
    $entity_bundle = $entity->bundle();

    if ($entity_bundle == 'remote_video') {
      $variables['provider'] = $entity->field_provider->value;
    }
  }
}
